INSERT INTO nestnavigate.amenity (id, name, category, sub_category) VALUES
-- Land Amenities
(UUID(), 'Electricity Connection', 'LAND', 'Infrastructure'),
(UUID(), 'Water Supply', 'LAND', 'Infrastructure'),
(UUID(), 'Sewage Connection', 'LAND', 'Infrastructure'),
(UUID(), 'Fencing', 'LAND', 'Security'),
(UUID(), 'Road Access', 'LAND', 'Infrastructure'),
(UUID(), 'Gated Access', 'LAND', 'Security'),
(UUID(), 'Irrigation', 'LAND', 'Infrastructure'),
(UUID(), 'Zoning Approval', 'LAND', 'Legal'),
(UUID(), 'Drainage System', 'LAND', 'Infrastructure'),
(UUID(), 'Site Office', 'LAND', 'Utility'),
(UUID(), 'Landscaping', 'LAND', 'Aesthetics'),
(UUID(), 'Borewell', 'LAND', 'Utility'),
(UUID(), 'Street Lighting', 'LAND', 'Infrastructure'),
(UUID(), 'Perimeter Wall', 'LAND', 'Security'),
(UUID(), 'Easement', 'LAND', 'Legal'),

-- Residential Amenities
(UUID(), 'Gym', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Swimming Pool', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Parking', 'RESIDENTIAL', 'Convenience'),
(UUID(), 'Elevator', 'RESIDENTIAL', 'Convenience'),
(UUID(), 'Security', 'RESIDENTIAL', 'Security'),
(UUID(), 'Power Backup', 'RESIDENTIAL', 'Utility'),
(UUID(), 'Wi-Fi', 'RESIDENTIAL', 'Connectivity'),
(UUID(), 'Air Conditioning', 'RESIDENTIAL', 'Comfort'),
(UUID(), 'Heating', 'RESIDENTIAL', 'Comfort'),
(UUID(), 'Balcony', 'RESIDENTIAL', 'Aesthetics'),
(UUID(), 'Garden', 'RESIDENTIAL', 'Aesthetics'),
(UUID(), 'Playground', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Community Hall', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Clubhouse', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Jogging Track', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Sports Facilities', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Home Automation', 'RESIDENTIAL', 'Technology'),
(UUID(), 'Intercom', 'RESIDENTIAL', 'Connectivity'),
(UUID(), 'Maintenance Staff', 'RESIDENTIAL', 'Utility'),
(UUID(), 'Rainwater Harvesting', 'RESIDENTIAL', 'Sustainability'),
(UUID(), 'Fire Safety', 'RESIDENTIAL', 'Safety'),
(UUID(), 'Waste Disposal', 'RESIDENTIAL', 'Utility'),
(UUID(), 'Library', 'RESIDENTIAL', 'Recreational'),
(UUID(), 'Reserve Parking', 'RESIDENTIAL', 'Convenience'),
(UUID(), 'Visitor Parking', 'RESIDENTIAL', 'Convenience'),
(UUID(), 'Pet Friendly', 'RESIDENTIAL', 'Comfort'),
(UUID(), 'Servant Room', 'RESIDENTIAL', 'Convenience'),
(UUID(), 'Internet', 'RESIDENTIAL', 'Connectivity'),
(UUID(), 'TV Cable', 'RESIDENTIAL', 'Connectivity'),
(UUID(), 'Water Purifier', 'RESIDENTIAL', 'Utility'),
(UUID(), 'Lift', 'RESIDENTIAL', 'Convenience'),
(UUID(), 'Pent House', 'RESIDENTIAL', 'Luxury'),

-- Commercial Amenities
(UUID(), 'Conference Room', 'COMMERCIAL', 'Workspace'),
(UUID(), 'Café', 'COMMERCIAL', 'Recreational'),
(UUID(), 'Pantry', 'COMMERCIAL', 'Convenience'),
(UUID(), 'Reception', 'COMMERCIAL', 'Convenience'),
(UUID(), 'Loading Docks', 'COMMERCIAL', 'Utility'),
(UUID(), 'High-Speed Internet', 'COMMERCIAL', 'Connectivity'),
(UUID(), 'CCTV', 'COMMERCIAL', 'Security'),
(UUID(), 'Fire Alarm', 'COMMERCIAL', 'Safety'),
(UUID(), 'Emergency Exit', 'COMMERCIAL', 'Safety'),
(UUID(), 'Continuous Water Supply', 'COMMERCIAL', 'Utility'),
(UUID(), 'Central Heating', 'COMMERCIAL', 'Comfort'),
(UUID(), 'Central Cooling', 'COMMERCIAL', 'Comfort'),
(UUID(), 'Mail Room', 'COMMERCIAL', 'Convenience'),
(UUID(), 'Server Room', 'COMMERCIAL', 'Technology'),
(UUID(), 'Business Lounge', 'COMMERCIAL', 'Recreational'),
(UUID(), 'Multi-Level Parking', 'COMMERCIAL', 'Convenience'),
(UUID(), 'Near Public Transport', 'COMMERCIAL', 'Accessibility'),
(UUID(), 'Shuttle Service', 'COMMERCIAL', 'Convenience'),

-- PG Amenities
(UUID(), 'Furnished Rooms (Bed, Table, Chair, Wardrobe)', 'PG', 'General'),
(UUID(), 'Electricity', 'PG', 'General'),
(UUID(), 'Continuous Water Supply', 'PG', 'General'),
(UUID(), 'Wi-Fi / High-Speed Internet', 'PG', 'General'),
(UUID(), 'Attached Bathrooms', 'PG', 'General'),
(UUID(), 'Laundry Facilities', 'PG', 'General'),
(UUID(), 'Housekeeping Services', 'PG', 'General'),
(UUID(), 'Power Backup', 'PG', 'General'),
(UUID(), 'Mess/Meals (Breakfast, Lunch, Dinner)', 'PG', 'Food & Dining'),
(UUID(), 'Shared Kitchen (For Self-Cooking)', 'PG', 'Food & Dining'),
(UUID(), 'Refrigerator', 'PG', 'Food & Dining'),
(UUID(), 'CCTV Surveillance', 'PG', 'Security'),
(UUID(), 'Biometric/Key Card Access', 'PG', 'Security'),
(UUID(), '24/7 Security Guard', 'PG', 'Security'),
(UUID(), 'Common Lounge/TV Area', 'PG', 'Recreational'),
(UUID(), 'Indoor Games (Chess, Carrom, etc.)', 'PG', 'Recreational'),
(UUID(), 'Gym/Fitness Room', 'PG', 'Recreational'),
(UUID(), 'Air Conditioning/Heating', 'PG', 'Convenience'),
(UUID(), 'Parking Facilities (For Two-Wheelers/Cars)', 'PG', 'Convenience'),
(UUID(), 'Public Transport Accessibility', 'PG', 'Convenience'),
(UUID(), 'Nearby Markets', 'PG', 'Convenience'),
(UUID(), 'Shuttle Service', 'PG', 'Convenience'),
(UUID(), 'Visitor Policy', 'PG', 'Miscellaneous'),
(UUID(), 'Storage Space', 'PG', 'Miscellaneous'),
(UUID(), 'Drinking Water Facility (RO/Filter)', 'PG', 'Miscellaneous');
