name: Java CI pipeline

on:
  push:
    branches: [ "temp" ]  # Trigger pipeline on push to "temp" branch

jobs:
  build:
    runs-on: ubuntu-latest # Runs the job on the latest Ubuntu 

    # Define environment variables at the job level
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
      SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
      SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
      SECURITY_JWT_SECRET_KEY: ${{ secrets.SECURITY_JWT_SECRET_KEY }}
      # SECURITY_JWT_EXPIRATION_TIME: ${{ secrets.SECURITY_JWT_EXPIRATION_TIME }}
      # SECURITY_JWT_REFRESH_TOKEN_EXPIRATION: ${{ secrets.SECURITY_JWT_REFRESH_TOKEN_EXPIRATION }}
      SPRING_SECURITY_USER_NAME: ${{ secrets.SPRING_SECURITY_USER_NAME }}
      SPRING_SECURITY_USER_PASSWORD: ${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
      # TOMCAT_USERNAME: ${{secrets.TOMCAT_USERNAME}}
      # TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      SMB_SERVER_ADDRESS: ${{ secrets.SMB_SERVER_ADDRESS }}
      SMB_SERVER_USERNAME: ${{ secrets.SMB_SERVER_USERNAME }}
      SMB_SERVER_PASSWORD: ${{ secrets.SMB_SERVER_PASSWORD }}
      

    steps:
      - uses: actions/checkout@v4  # Checkout code from the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Set up Java JDK 17
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Cache Maven dependencies

      - name: Build with Maven
        run: mvn clean install  # Run Maven to clean and build the project

      - name: Upload Artifact
        if: success()  # Only execute if the build is successful
        uses: actions/upload-artifact@v3
        with:
          name: nest-navigate  # Name of the artifact
          path: target/Nest-Navigate-0.0.1-SNAPSHOT.war  # Correct the path to where the WAR file is located (default is target/)

      - name: Deploy WAR to Local Tomcat
        if: success()  # Only execute if the artifact was uploaded successfully
        run: |
          echo "SETTING SECRETS TO VARIABLES IN VM"
          export SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
          export SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          export SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          export SPRING_MAIL_HOST=${{ secrets.SPRING_MAIL_HOST }}
          export SPRING_MAIL_PORT=${{ secrets.SPRING_MAIL_PORT }}
          export SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}
          export SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}
          export SECURITY_JWT_SECRET_KEY=${{ secrets.SECURITY_JWT_SECRET_KEY }}
          export SECURITY_JWT_EXPIRATION_TIME=${{ secrets.SECURITY_JWT_EXPIRATION_TIME }}
          export SECURITY_JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.SECURITY_JWT_REFRESH_TOKEN_EXPIRATION }}
          export SPRING_SECURITY_USER_NAME=${{ secrets.SPRING_SECURITY_USER_NAME }}
          export SPRING_SECURITY_USER_PASSWORD=${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
          export SMB_SERVER_ADDRESS=${{ secrets.SMB_SERVER_ADDRESS }}
          export SMB_SERVER_USERNAME=${{ secrets.SMB_SERVER_USERNAME }}
          export SMB_SERVER_PASSWORD=${{ secrets.SMB_SERVER_PASSWORD }}
          echo "setting PATH VARIABLE IN VM"
          #set PATH variable
          export PATH=$SPRING_DATASOURCE_URL:$PATH
          export PATH=$SPRING_DATASOURCE_USERNAME:$PATH
          export PATH=$SPRING_DATASOURCE_PASSWORD:$PATH
          export PATH=$SECURITY_JWT_SECRET_KEY:$PATH
          export PATH=$SPRING_MAIL_HOST:$PATH
          export PATH=$SPRING_MAIL_PORT:$PATH
          export PATH=$SPRING_MAIL_USERNAME:$PATH
          export PATH=$SPRING_MAIL_PASSWORD:$PATH
          export PATH=$SPRING_SECURITY_USER_NAME:$PATH
          export PATH=$SPRING_SECURITY_USER_PASSWORD:$PATH
          export PATH=$SMB_SERVER_ADDRESS:$PATH
          export PATH=$SMB_SERVER_USERNAME:$PATH
          export PATH=$SMB_SERVER_PASSWORD:$PATH
          # Deploy the WAR file using curl
          curl -u ${{secrets.TOMCAT_USERNAME}}:${{ secrets.TOMCAT_PASSWORD }} \
            -T target/Nest-Navigate-0.0.1-SNAPSHOT.war \
            "http://103.127.31.155:8080/manager/text/deploy?path=/NN&update=true"
